name: Test

env:
  FORCE_COLOR: 1

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: [test]

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - 'ember-lts-3.12'
          - 'ember-release'
          - 'ember-beta'
          - 'ember-canary'
          - 'ember-default-with-jquery'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --no-lockfile
      - name: Test
        run: yarn ember
